import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Header from "../components/Header/Header"
import Link from 'next/link'
import { motion } from 'framer-motion'


export default function Home() {
  return (
    <div className={styles.container}>
              <Head>
        <title>Testing scroll animation</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
    <Header/>
    

    <motion.h1 layoutId="store-title" class="store-title">Produtos</motion.h1>
    <div className={styles['product-container']}>
     
      {[
        "Black Flame", "Blue Flame", "Green Heat", 
        "bottle_red", "White Premium", "Premium 18 years Old"
      ].map(product => (
        <Link href={product}><a>
          
      <motion.img 
      layoutId={product}
      className={styles.image} 
      src={product + ".png"} 
      animate={{ scale: 1 }}
      whileHover={{ scale: 1.2}}
      />
      </a>
      </Link>
      )
      )}
      
    </div>
   </div>
  )
}
